name: A demo workflow
on:
  push:
    paths-ignore:
    - '.github/**'
    - 'action-a/**'

jobs:
  build:
    name: Demo build job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./action-a
      with:
        MY_NAME: "David"
