name: A demo workflow
on:
  # Triggered by commit, excluding action files
  push:
    paths-ignore:
    - 'action-a/**'
env:
  IN_NAME: SCB
  
jobs:
  build:
    name: Demo build job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./action-a
      with:
        MY_NAME: $IN_NAME
